security:
 oauth2:
  client:
   clientId: CLIENT_APP_ID
   clientSecret: CLIENT_SECRETE
   accessTokenUri: https://graph.facebook.com/oauth/access_token
   userAuthorizationUri: https://www.facebook.com/dailog/oauth
   tokenName: oauth_token
   authenticationScheme: query
   clientAuthenticationScheme: form

  resource:
   userInfoUri: https://graph.facebook.com/oauth
server:
  port : 7777